/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const FeeStatus = IDL.Record({
  'paid' : IDL.Bool,
  'student' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'grade' : IDL.Opt(IDL.Text),
});
export const Grade = IDL.Record({ 'subject' : IDL.Text, 'score' : IDL.Nat });
export const TimetableEntry = IDL.Record({
  'day' : IDL.Text,
  'subject' : IDL.Text,
  'time' : IDL.Text,
  'grade' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGrade' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
  'addSubjectAssignment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'addTimetableEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generatePasswordResetToken' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllFees' : IDL.Func([], [IDL.Vec(FeeStatus)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGrades' : IDL.Func([IDL.Principal], [IDL.Vec(Grade)], ['query']),
  'getStudentFees' : IDL.Func([IDL.Principal], [FeeStatus], ['query']),
  'getSubjectsForTeacher' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getTimetableForGrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTokenValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeeStatus' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyPasswordResetToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const FeeStatus = IDL.Record({
    'paid' : IDL.Bool,
    'student' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'grade' : IDL.Opt(IDL.Text),
  });
  const Grade = IDL.Record({ 'subject' : IDL.Text, 'score' : IDL.Nat });
  const TimetableEntry = IDL.Record({
    'day' : IDL.Text,
    'subject' : IDL.Text,
    'time' : IDL.Text,
    'grade' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGrade' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
    'addSubjectAssignment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'addTimetableEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generatePasswordResetToken' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllFees' : IDL.Func([], [IDL.Vec(FeeStatus)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGrades' : IDL.Func([IDL.Principal], [IDL.Vec(Grade)], ['query']),
    'getStudentFees' : IDL.Func([IDL.Principal], [FeeStatus], ['query']),
    'getSubjectsForTeacher' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getTimetableForGrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTokenValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeeStatus' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyPasswordResetToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };