/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface FeeStatus {
  'paid' : boolean,
  'student' : Principal,
  'amount' : bigint,
}
export interface Grade { 'subject' : string, 'score' : bigint }
export type Time = bigint;
export interface TimetableEntry {
  'day' : string,
  'subject' : string,
  'time' : string,
  'grade' : string,
}
export interface UserProfile {
  'subject' : [] | [string],
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'grade' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Grades Management
   */
  'addGrade' : ActorMethod<[Principal, string, bigint], undefined>,
  /**
   * / Subject Assignment Management
   */
  'addSubjectAssignment' : ActorMethod<[Principal, string], undefined>,
  /**
   * / Timetable Management
   */
  'addTimetableEntry' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Password Reset Management
   */
  'generatePasswordResetToken' : ActorMethod<[Principal], string>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllFees' : ActorMethod<[], Array<FeeStatus>>,
  /**
   * / User Profile Management
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGrades' : ActorMethod<[Principal], Array<Grade>>,
  'getStudentFees' : ActorMethod<[Principal], FeeStatus>,
  'getSubjectsForTeacher' : ActorMethod<[Principal], Array<string>>,
  'getTimetableForGrade' : ActorMethod<[string], Array<TimetableEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTokenValid' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Fee Management
   */
  'setFeeStatus' : ActorMethod<[Principal, bigint, boolean], undefined>,
  /**
   * / Contact Form Management
   */
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'verifyPasswordResetToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];